### ISSUE TITLE
can't see any entitities

### ISSUE THREAD

**Issue by MasterKyle08** [YassaaaTU/ALOE#1]
I cannot see items on the ground or any entities in the world. I am playing singleplayer

**Comment by YassaaaTU** [comment]
can you send logs or images?

**Comment by YassaaaTU** [comment]
> https://www.dropbox.com/s/k6byzgfqyfgf54p/latest.log?dl=0
> 
> theres the log

https://mclo.gs/
use this site to post logs

**Comment by MasterKyle08** [comment]
i just restarted my game and its fine now
